export const Gents ={
    title: "Gents Fashion",
    image1:"assets/men/men1.jpg",
    image2:"assets/men/men2.jpg",
    image3:"assets/men/men3.jpg",
    image4:"assets/men/men1.jpg",
    image5:"assets/men/men8.jpg",
    image6:"assets/men/men6.jpg",
   // image7:"assets/men/men7.jpg",
   // image8:"assets/men/men8.jpg",
   // image9:"assets/men/men9.jpg",
   // image10:"assets/men/men10.webp",
    price1: "1059 INR",
    price2: "959 INR",
    price3: "859 INR",
    price4: "759 INR",
    price5: "659 INR",
    price6: "559 INR",
  //price7: "459 INR",
  //price8: "359 INR",
  //  price9: "259 INR",
   // price10: "159 INR",
}
export const Ladies ={
    title: "Ladies Fashion",
    image1:"assets/women/wmn1.jpg",
    image2:"assets/women/wmn2.jpg",
    image3:"assets/women/wmn3.jpg",
    image4:"assets/women/wmn4.jpg",
    image5:"assets/women/wmn5.jpg",
    image6:"assets/women/wmn6.jpg",
   
    price1: "190 INR",
    price2: "759 INR",
    price3: "859 INR",
    price4: "459 INR",
    price5: "659 INR",
    price6: "559 INR",
   // price7: "259 INR",
   // price8: "359 INR",
   // price9: "159 INR",
    // price10: "190 INR",
}
export const Childrens ={
    title: "Childrens Fashion",
   image1:"assets/children/chld1.webp",
   image2:"assets/children/chld2.jpg",
   image3:"assets/children/chld3.webp",
   image4:"assets/children/chld4.avif",
   image5:"assets/children/chld5.jpg",
   image6:"assets/children/chld6.jpg",
   image7:"assets/children/chld7.jpg",
   image8:"assets/children/chld8.jpg",
   image9:"assets/children/chld9.jpg",
   image10:"assets/children/chld10.jpg",
    price1: "190 INR",
    price2: "751 INR",
    price3: "857 INR",
    price4: "456 INR",
    price5: "655 INR",
    price6: "554 INR",
   //  price7: "259 INR",
   // price8: "350 INR",
   // price9: "159 INR",
   // price10: "190 INR",
}